"""added many more fields for attributes of the place

Revision ID: 046fbf6de96b
Revises: e019c7ab7afa
Create Date: 2022-04-14 14:43:08.730528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046fbf6de96b'
down_revision = 'e019c7ab7afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('price_level', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('service_charge_rate', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('vat_included', sa.Boolean(), nullable=True))
    op.add_column('addresses', sa.Column('parking_avail', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('parking_note', sa.Text(), nullable=True))
    op.add_column('addresses', sa.Column('parking_fee', sa.Boolean(), nullable=True))
    op.add_column('addresses', sa.Column('free_wifi', sa.Boolean(), nullable=True))
    op.add_column('addresses', sa.Column('seating_avail', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('pet_friendly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'pet_friendly')
    op.drop_column('addresses', 'seating_avail')
    op.drop_column('addresses', 'free_wifi')
    op.drop_column('addresses', 'parking_fee')
    op.drop_column('addresses', 'parking_note')
    op.drop_column('addresses', 'parking_avail')
    op.drop_column('addresses', 'vat_included')
    op.drop_column('addresses', 'service_charge_rate')
    op.drop_column('addresses', 'price_level')
    # ### end Alembic commands ###
