"""added geometry, lat, lon fields to the address model

Revision ID: 109cae8030f7
Revises: fcfab66ef33e
Create Date: 2022-04-13 13:28:23.312618

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '109cae8030f7'
down_revision = 'fcfab66ef33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('addresses', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('wkb_geometry', geoalchemy2.types.Geometry(geometry_type='POINT',
                                                                                    srid=4326,
                                                                                    from_text='ST_GeomFromEWKT',
                                                                                    name='geometry'), nullable=True))
    # op.create_index('idx_addresses_wkb_geometry', 'addresses', ['wkb_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_addresses_wkb_geometry', table_name='addresses', postgresql_using='gist', postgresql_ops={})
    op.drop_column('addresses', 'wkb_geometry')
    op.drop_column('addresses', 'lon')
    op.drop_column('addresses', 'lat')
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
