"""moved place properties from address model to the cafe model

Revision ID: 774c488dcbea
Revises: d88518029281
Create Date: 2022-04-14 16:23:37.647923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '774c488dcbea'
down_revision = 'd88518029281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'parking_note')
    op.drop_column('addresses', 'pet_friendly')
    op.drop_column('addresses', 'service_charge_rate')
    op.drop_column('addresses', 'parking_fee')
    op.drop_column('addresses', 'free_wifi')
    op.drop_column('addresses', 'vat_included')
    op.drop_column('addresses', 'seating_avail')
    op.drop_column('addresses', 'parking_avail')
    op.drop_column('addresses', 'price_level')
    op.add_column('cafes', sa.Column('price_level', sa.Integer(), nullable=True))
    op.add_column('cafes', sa.Column('service_charge_rate', sa.Float(), nullable=True))
    op.add_column('cafes', sa.Column('vat_included', sa.Boolean(), nullable=True))
    op.add_column('cafes', sa.Column('parking_avail', sa.String(), nullable=True))
    op.add_column('cafes', sa.Column('parking_note', sa.Text(), nullable=True))
    op.add_column('cafes', sa.Column('parking_fee', sa.Boolean(), nullable=True))
    op.add_column('cafes', sa.Column('free_wifi', sa.Boolean(), nullable=True))
    op.add_column('cafes', sa.Column('seating_avail', sa.String(), nullable=True))
    op.add_column('cafes', sa.Column('pet_friendly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafes', 'pet_friendly')
    op.drop_column('cafes', 'seating_avail')
    op.drop_column('cafes', 'free_wifi')
    op.drop_column('cafes', 'parking_fee')
    op.drop_column('cafes', 'parking_note')
    op.drop_column('cafes', 'parking_avail')
    op.drop_column('cafes', 'vat_included')
    op.drop_column('cafes', 'service_charge_rate')
    op.drop_column('cafes', 'price_level')
    op.add_column('addresses', sa.Column('price_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('parking_avail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('seating_avail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('vat_included', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('free_wifi', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('parking_fee', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('service_charge_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('pet_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('parking_note', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
