"""added address components to store data from google maps

Revision ID: e019c7ab7afa
Revises: 109cae8030f7
Create Date: 2022-04-14 13:49:21.937576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e019c7ab7afa'
down_revision = '109cae8030f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('subdistrict', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('postal_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'postal_code')
    op.drop_column('addresses', 'subdistrict')
    # ### end Alembic commands ###
